---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-external
spec:
  replicas: 1
  version: 5.0.0
  adminCredentials: ops-manager-admin-secret
  externalConnectivity:
    type: NodePort
    port: 30100
  applicationDatabase:
    members: 3
    version: 4.4.4-ent
    persistent: true
  backup:
    enabled: false
