---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-project
  namespace: mongodb
data:
  baseUrl: http://ops-manager-external-svc.mongodb.svc.cluster.local:8080
---
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb
stringData:
  user: gsazdasg
  publicApiKey: fb8680b4-a703-428d-b3e3-ef61f5ba7297