---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-project
  namespace: mongodb
data:
  baseUrl: http://ops-manager-external-svc.mongodb.svc.cluster.local:8080
---
apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
  namespace: mongodb
stringData:
  user: gsazdasg
  publicApiKey: fb8680b4-a703-428d-b3e3-ef61f5ba7297
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-standalone
  namespace: mongodb
spec:
  version: 4.4.0-ent
  type: Standalone
  opsManager:
    configMapRef:
      name: my-project
  credentials: organization-secret
  persistent: false
  podSpec:
    podTemplate:
      spec:        
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "2"
                memory: 700M
              requests:
                cpu: "1"
                memory: 500M