---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager-external
  namespace: mongodb
spec:
  replicas: 1
  version: 5.0.0
  adminCredentials: ops-manager-admin-secret
  externalConnectivity:
    type: NodePort
    port: 30100
  backup:
    enabled: false
  applicationDatabase:
    version: "4.4.4-ent"
    members: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ops-manager-ports
  namespace: mongodb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 8080